Repository kylehipz/goku, pull requests merged in 2024-01, with the labels that each got.

#4 Infra/ci
  .github/workflows/github-actions-demo.yml
Labels: development

#16 added swagger for documentation
  services/microservices/nest-cli.json
  services/microservices/package-lock.json
  services/microservices/package.json
  services/microservices/src/main.ts
Labels: documentation, development, backend, nestjs

#17 delete microservice folders for nestjs
  services/auth/package.json
  services/home-feed/package.json
  services/microservices/.eslintrc.js
  services/microservices/.gitignore
  services/microservices/.prettierrc
  services/microservices/README.md
  services/microservices/nest-cli.json
  services/microservices/package-lock.json
  services/microservices/package.json
  services/microservices/src/app.controller.spec.ts
  services/microservices/src/app.controller.ts
  services/microservices/src/app.module.ts
  services/microservices/src/app.service.ts
  services/microservices/src/main.ts
  services/microservices/test/app.e2e-spec.ts
  services/microservices/test/jest-e2e.json
  services/microservices/tsconfig.build.json
  services/microservices/tsconfig.json
  services/search/package.json
  services/upload/package.json
Labels: documentation, backend, nestjs
